<a href="https://colab.research.google.com/github/Ph1so/Titanic/blob/main/Titanic_Phi_Nguyen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Install Dataset*

In [ ]:
!pip install -q kaggle

In [ ]:
from google.colab import files
files.upload()

In [ ]:
#create kaggle folder
! mkdir ~/.kaggle

In [ ]:
#copy json file to new folder
! cp kaggle.json ~/.kaggle/

In [ ]:
#give json files perms
! chmod 600 ~/.kaggle/kaggle.json

In [ ]:
#list data sets in kaggle
! kaggle datasets list

In [ ]:
!kaggle competitions download -c titanic

In [ ]:
!unzip titanic.zip

Archive:  titanic.zip
  inflating: gender_submission.csv
  inflating: test.csv
  inflating: train.csv

In [ ]:
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import math

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split


data = pd.read_csv('train.csv', usecols = [1,2,4,5,6,7])

data.head()

#replace NA values
data['Age'].fillna(0, inplace=True)

In [ ]:
data = pd.get_dummies(data, drop_first = True)
data.sample(50)

     Survived  Pclass   Age  SibSp  Parch  Sex_male
392         0       3  28.0      2      0         1
655         0       2  24.0      2      0         1
816         0       3  23.0      0      0         0
203         0       3  45.5      0      0         1
272         1       2  41.0      0      1         0
634         0       3   9.0      3      2         0
814         0       3  30.5      0      0         1
458         1       2  50.0      0      0         0
224         1       1  38.0      1      0         1
231         0       3  29.0      0      0         1
331         0       1  45.5      0      0         1
311         1       1  18.0      2      2         0
614         0       3  35.0      0      0         1
363         0       3  35.0      0      0         1
319         1       1  40.0      1      1         0
850         0       3   4.0      4      2         1
282         0       3  16.0      0      0         1
432         1       2  42.0      1      0         0
21          1       2  34.0      0      0         1
463         0       2  48.0      0      0         1
754         1       2  48.0      1      2         0
322         1       2  30.0      0      0         0
551         0       2  27.0      0      0         1
205         0       3   2.0      0      1         0
466         0       2   0.0      0      0         1
765         1       1  51.0      1      0         0
877         0       3  19.0      0      0         1
770         0       3  24.0      0      0         1
177         0       1  50.0      0      0         0
144         0       2  18.0      0      0         1
192         1       3  19.0      1      0         0
457         1       1   0.0      1      0         0
335         0       3   0.0      0      0         1
673         1       2  31.0      0      0         1
492         0       1  55.0      0      0         1
444         1       3   0.0      0      0         1
254         0       3  41.0      0      2         0
141         1       3  22.0      0      0         0
555         0       1  62.0      0      0         1
751         1       3   6.0      0      1         1
582         0       2  54.0      0      0         1
820         1       1  52.0      1      1         0
298         1       1   0.0      0      0         1
854         0       2  44.0      1      0         0
198         1       3   0.0      0      0         0
864         0       2  24.0      0      0         1
131         0       3  20.0      0      0         1
312         0       2  26.0      1      1         0
601         0       3   0.0      0      0         1
769         0       3  32.0      0      0         1

In [ ]:
xtrain, xtest, ytrain, ytest = train_test_split(data.drop('Survived', axis=1), data['Survived'])

In [ ]:
print(xtrain)
reg = LogisticRegression(solver = 'saga')
reg.fit(xtrain, ytrain)

     Pclass   Age  SibSp  Parch  Sex_male
276       3  45.0      0      0         0
354       3   0.0      0      0         1
788       3   1.0      1      2         1
389       2  17.0      0      0         0
683       3  14.0      5      2         1
..      ...   ...    ...    ...       ...
833       3  23.0      0      0         1
444       3   0.0      0      0         1
325       1  36.0      0      0         0
574       3  16.0      0      0         1
805       3  31.0      0      0         1

[668 rows x 5 columns]

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

LogisticRegression(solver='saga')

In [ ]:
#read test csv file

test = pd.read_csv('test.csv', usecols = [1,3,4,5,6])

test.head()

test['Age'].fillna(0, inplace=True)

test = pd.get_dummies(test, drop_first = True)
test.sample(50)

print(test.loc[0])

Pclass       3.0
Age         34.5
SibSp        0.0
Parch        0.0
Sex_male     1.0
Name: 0, dtype: float64

In [ ]:
#create csv file
import csv

with open("titanic_submission.csv", mode = "w") as csvfile:
  fieldnames = ["PassengerId", "Survived"]
  writer = csv.DictWriter(csvfile, fieldnames = fieldnames)
  writer.writeheader()
  guess = 0
  for i in range(test['Age'].size):
    guess = reg.predict([test.loc[i]])[0]
    writer.writerow({"PassengerId": 892 + i, "Survived": guess})